### ISSUE TITLE
INSTALL: unknown type name 'byte'; did you mean 'CryptoPP::byte'?

### ISSUE THREAD

**Issue by jordanwlee** [DECENTfoundation/DECENT-Network#253]
Trying to install on Mac OS. Got everything done except the last two install commands which generate the errors below. It's showing I have 9 of these errors. Not sure how to fix. 

```
dev/DECENTfoundation/DECENT-Network/libraries/encrypt/encryptionutils.cpp:304:7: error: 
      unknown type name 'byte'; did you mean 'CryptoPP::byte'?
      byte messageBytes[DECENT_EL_GAMAL_GROUP_ELEMENT_SIZE];
      ^~~~
      CryptoPP::byte
```

**Comment by MilanFranc** [comment]
Hello, what version of CryptoPP are you using ? I have version 5.6.5 and the symbol 'byte' is defined in config.h of the CryptoPP library.

line 230:  typedef unsigned char byte;		// put in global namespace to avoid ambiguity with other byte typedefs

**Comment by mpmansell** [comment]
It looks like this is an issue with more recent releases of the Crypto++ library.

Crypto++ v5.6.5 was used during development and it is recommended that anyone attempting to build from source should use this version. 

It can currently be downloaded from the official site (https://www.cryptopp.com/) through:
https://www.cryptopp.com/cryptopp565.zip

Documentation will be updated to clarify this.

**Comment by jordanwlee** [comment]
Thank you. At this point, I have uninstalled the current Crypto version and I am trying to figure out how to install an older version of Crypto 5.6.2 through terminal. I tried some message board info I found online but nothing seems to work. Does anyone have an idea of how this can be done?

**Comment by eviljames** [comment]
Hello, I've created a quick PR that should resolve this issue.

https://github.com/DECENTfoundation/DECENT-Network/pull/305

**Comment by MilanFranc** [comment]
Hello, I have fixed this issue in #307 to work with old (5.6.5) and new (6.0.0 and newer) versions of CryptoPP.
It will be released with next release.
