### PR TITLE
Add CryptoPP:: namespace declarations to fix #253

### LINKED ISSUE #253: INSTALL: unknown type name 'byte'; did you mean 'CryptoPP::byte'?
Trying to install on Mac OS. Got everything done except the last two install commands which generate the errors below. It's showing I have 9 of these errors. Not sure how to fix. 

```
dev/DECENTfoundation/DECENT-Network/libraries/encrypt/encryptionutils.cpp:304:7: error: 
      unknown type name 'byte'; did you mean 'CryptoPP::byte'?
      byte messageBytes[DECENT_EL_GAMAL_GROUP_ELEMENT_SIZE];
      ^~~~
      CryptoPP::byte
```

### PR DESCRIPTION
**Pull request by eviljames**
Was trying to build on a recent MacOS with CryptoPP 7.0.0 from Homebrew, and got stung by #253 - so here is a quick fix for it.

### CODE REVIEW

**Comment by MilanFranc** [comment]
Thank you for the fix, but we have to fix it that works for old and new version of CryptoPP. Closing this pull request.
